// Manual location list (per spec §5: no Google Places integration yet).
// CABA neighborhoods first, then other major Argentine cities.
export const LOCATIONS: string[] = [
  'Palermo, CABA',
  'Belgrano, CABA',
  'Recoleta, CABA',
  'Caballito, CABA',
  'Villa Crespo, CABA',
  'Almagro, CABA',
  'Flores, CABA',
  'Núñez, CABA',
  'Colegiales, CABA',
  'Villa Urquiza, CABA',
  'San Telmo, CABA',
  'Boedo, CABA',
  'Barracas, CABA',
  'Liniers, CABA',
  'Villa Devoto, CABA',
  'Balvanera, CABA',
  'Retiro, CABA',
  'Puerto Madero, CABA',
  'San Isidro, GBA',
  'Vicente López, GBA',
  'Tigre, GBA',
  'La Plata, Buenos Aires',
  'Mar del Plata, Buenos Aires',
  'Rosario, Santa Fe',
  'Córdoba, Córdoba',
  'Mendoza, Mendoza',
  'Salta, Salta',
  'San Miguel de Tucumán, Tucumán',
  'Neuquén, Neuquén',
  'Bariloche, Río Negro',
];
